version: '3.4'

services:
  redis:
    container_name: clean_architecture_redis
    image: "redis"
    ports:
      - "6379:6379"
  db:
    container_name: clean_architecture_mysql
    image: mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
  clean_architecture:
    container_name: clean_architecture
    build:
      context: .
      target: test
    volumes:
      - ./src/:/home/qustodio/clean_architecture
    ports:
      - "8000:80"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  celery:
    container_name: clean_architecture_celery
    build:
      context: .
      target: test
    command: celery -A project.celery worker -l info
    depends_on:
      - "redis"
    env_file:
      - ./.env
    volumes:
      - ./src/:/home/qustodio/clean_architecture
