# Generated by Django 3.2.15 on 2022-09-27 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.CharField(max_length=500)),
                ('provider', models.IntegerField(choices=[(1, 'Janto')])),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('max_price', models.FloatField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'PendingReview')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['original_id'], name='events_cont_origina_8bb321_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['provider'], name='events_cont_provide_976990_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['original_id', 'provider'], name='events_cont_origina_bde360_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='events_cont_start_d_874f73_idx'),
        ),
    ]
